
name: 'Docker Stack Deploy Action'
description: 'Deploy a Docker stack on a Docker Swarm'
author: 'kitconcept GmbH'
branding:
  icon: 'truck'
  color: 'red'
inputs:
  registry:
    description: 'Container registry to use'
    required: false
    default: ""
  username:
    description: 'Container registry username'
    required: false
    default: ""
  password:
    description: 'Container registry password'
    required: false
    default: ""
  remote_host:
    description: 'Host running Docker Swarm'
    required: true
  remote_port:
    description: 'SSH port on the host running Docker Swarm'
    required: false
    default: "22"
  remote_user:
    description: 'User to connect to remote host'
    required: true
  remote_private_key:
    description: 'Private key used for ssh authentication'
    required: true
  deploy_timeout:
    description: "Timeout for the deploy check (in seconds)"
    required: false
    default: "600"
  resolve_image:
    description: "Query the registry to resolve image digest and supported platforms before deploy (Supported values: always, changed, never)"
    default: "always"
  prune:
    description: "Prune services that are not defined in the stack file (1 to enable, 0 to disable)"
    default: "0"
  stack_file:
    description: "Path to the stack file to be used for deploy"
    required: true
  stack_name:
    description: "Name of the stack to be deployed"
    required: true
  stack_param:
    description: "Additional stack parameter value"
    required: false
    default: ""
  env_file:
    description: "Additional environment variables in the format VAR_01=VALUE\nVAR_02=VALUE"
    required: false
    default: ""
  debug:
    description: "Debug information"
    required: false
    default: "0"
  scale_after:
    description: "Service to scale after successful deploy (example: servicename=1)"
    default: ""
runs:
  using: 'docker'
  image: 'docker://ghcr.io/kitconcept/docker-stack-deploy:latest'
  env:
    REGISTRY: ${{ inputs.registry }}
    USERNAME: ${{ inputs.username }}
    PASSWORD: ${{ inputs.password }}
    REMOTE_HOST: ${{ inputs.remote_host }}
    REMOTE_PORT: ${{ inputs.remote_port }}
    REMOTE_USER: ${{ inputs.remote_user }}
    REMOTE_PRIVATE_KEY: ${{ inputs.remote_private_key }}
    DEPLOY_TIMEOUT: ${{ inputs.deploy_timeout }}
    RESOLVE_IMAGE: ${{ inputs.resolve_image }}
    PRUNE: ${{ inputs.prune }}
    STACK_FILE: ${{ inputs.stack_file }}
    STACK_NAME: ${{ inputs.stack_name }}
    STACK_PARAM: ${{ inputs.stack_param }}
    ENV_FILE: ${{ inputs.env_file }}
    DEBUG: ${{ inputs.debug }}
    SCALE_AFTER: ${{ inputs.scale_after }}
